package com.chen.mvp.local.table;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

/**
 * Entity mapped to table NEWS_TYPE_INFO.
 */
public class NewsTypeInfo {

    @Id(autoincrement = true)
    private Long id;
    /** Not-null value. */
    private String name;
    private String typeId;
    @Generated(hash = 215923915)
    public NewsTypeInfo() {
    }

    public NewsTypeInfo(Long id) {
        this.id = id;
    }
    @Generated(hash = 1707873593)
    public NewsTypeInfo(Long id, String name, String typeId) {
        this.id = id;
        this.name = name;
        this.typeId = typeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

}
